server:
  port: 8090

# Fallback URLs are for local development only. Set AUTH_SERVICE_URL and USER_SERVICE_URL env vars in all other environments.
services:
  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:8081}
  user-service-url: ${USER_SERVICE_URL:http://localhost:8080}
  order-service-url: ${ORDER_SERVICE_URL:http://localhost:8082}
  payment-service-url: ${PAYMENT_SERVICE_URL:http://localhost:8083}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${services.auth-service-url}
              predicates:
                - Path=/api/v1/auth/login,/api/v1/auth/refresh,/api/v1/auth/logout

            - id: user-service
              uri: ${services.user-service-url}
              predicates:
                - Path=/api/v1/users/**

            - id: order-service
              uri: ${services.order-service-url}
              predicates:
                - Path=/api/v1/orders/**

            - id: payment-service
              uri: ${services.payment-service-url}
              predicates:
                - Path=/api/v1/payments/**

            - id: user-cards
              uri: ${services.user-service-url}
              predicates:
                - Path=/api/v1/cards/**

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${AUTH_JWKS_URI:http://localhost:8081/oauth2/jwks}
