server:
  port: 8090

services:
  auth-service-url: ${AUTH_SERVICE_URL:http://localhost:8081}
  user-service-url: ${USER_SERVICE_URL:http://localhost:8080}

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: ${USER_SERVICE_URL:http://localhost:8080}
              predicates:
                - Path=/users/**
