server:
  port: 8080

spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: ${AUTH_SERVICE_URL:http://auth-service:8080}
              predicates:
                - Path=/auth/**

            - id: user-service
              uri: ${USER_SERVICE_URL:http://user-service:8080}
              predicates:
                - Path=/users/**
